doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '8.0'
            charset: utf8
            default_table_options:
                charset: utf8
                collate: utf8_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
